#!/usr/bin/perl

## fix up html help files generated by Rdconv for use outside of the 
## R help hierarchy

## - replace the stylsheet with one in the current dir
## - map links to "../../../doc/html/search/SearchObject.html?fname" with 
##   just fname.html

while (<>) {

  ## fix up the stylesheet
  s/[.\/]+doc\/html\/R.css/style.css/;

  ## fix up the links
  s/[.\/]+doc\/html\/search\/SearchObject.html\?([^\"]+)/\1.html/g;

  print;

}
