---
title: "autobuild tutorial"
author: "Raphael Winkelmann"
affiliation: "Institute Of Phonetic And Speech Processing (LMU Munich)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: vignettes.bib
vignette: >
  %\VignetteIndexEntry{autobuild tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
  
# WARNING: DOCUMENT STILL BEING WRITTEN!
  
# Introduction
  
The annotation of large complex multileveled hierachical speech databases is
a very time consuming laborious procedure. The *emuR* provides functions to
automate various bits of this proccedure to help with this laborious task.

This document describes how to automatically build hierachies for a given 

**emuDB**


The available function are:

- autobuild.linkFromTimes()
- autobuild.MapLevels()
- autobuild.Syllabify()



An important prereq: linkDefinition available!


## autobuild.linkFromTimes()

This function causes annotations at two levels *L1* and *L2* to be linked whenever the time(s) of the annotations at tier
*U* are within those of ttier *T*.


Given we have a a super-level of the form:

Lets load a demo database and add a new fake level to the database so we have
something to play with


```{r}
# load the package
library(emuR)
# get the path to the ae database that comes with the package
path2ae = system.file("extdata/emu/DBs/ae/", package = "emuR")
# load the database
ae = load.emuDB(path2ae, verbose = F)
# plot the phonetic level
# add linkDef.
  #tmpLinkDef = create.schema.linkDefinition(type='ONE_TO_MANY', superlevelName='Phonetic', sublevelName='Tone')
  #ae$DBconfig$linkDefinitions[[length(ae$DBconfig$linkDefinitions) + 1]] = tmpLinkDef 


```

and a sub-level of the form:

<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
  <rect width="100%" height="75" stroke-width="1" fill="#E7E7E7" stroke="rgb(0, 0, 0)" />
  <line x1="0" y1="0" x2="20%" y2="20%" fill="rgb(0, 0, 0)" stroke-width="5"  />
</svg>

- ONE\_TO\_MANY
- MANY\_TO\_MANY
- ONE\_TO\_ONE