---
title: "Version 2 of the Emu Query Language"
author: "Raphael Winkelmann & Klaus Jänsch"
affiliation: "Institute Of Phonetic And Speech Processing (LMU Munich)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: vignettes.bib
vignette: >
  %\VignetteIndexEntry{Version 2 of the Emu Query Language}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# WARNING: DOCUMENT STILL BEING WRITTEN!

# Introduction

This document formaly introduces and defines version 2 of the **E**mu 
**Q**uery **L**anguage (**EQL**).

# Extended Backus–Naur Form (EBNF)

most of the EBNF was adapted from [@john:2012a]

## Terminal symbols of EQL2 (operators) and their meaning.
## Sorted descending by their binding priority

| Operator | Meaning |
| --- | --- |
| # | Result modifier (projection) |
| , | Parameter list separator |
| == | Equality (new in version 2 of the EQL; for cleaner syntax)|
| = | Equality (optional; for backwards compatibility)|
| != | Unequality |
| =~ | Regular expression match
| !~ | Regular expression not match
| > | Greater than |
| >= | Equal or greater than  |
| < | Less than |
| >= | Equal or less than |
| \| | Alternatives separator |
| & | Conjunction of equal rank |
| ^ | Dominanceconjunction |
| -> | Sequenceoperator |

## Terminal symbols of EQL2 (brackets) and their meaning.

| Bracket | Meaning |
| --- | --- |
| ' | Quotes literal string |
| ( | Function parameter list begin |
| ) | Function parameter list end |
| &#91; | Sequence or dominance enclosing begin bracket  |
| &#93; | Sequence or dominance enclosing end bracketr |

## Terminal symbols of EQL2 (functions) and their meaning

| Function | Meaning |
| --- | --- |
| Start | Start | 
| Medial | Medial |
| End | Final |
| Num | Count |

## Nearly complete formal description of EMU query language EQL2

| X | Y |
| --- | --- |
| EQL | = KONJA \| SEQA \| DOMA; |
| DOMA | ='[',(KONJA|DOMA|SEQA),'ˆ',(KONJA|DOMA|SEQA),']'; (*Levels must be hierarchically or sequentially associated*) |
| SEQA | ='[',(KONJA|SEQA|DOMA),'->',(KONJA|SEQA|DOMA),']'; (*Levels must be linear associated*) |
| KONJA | = {'['},EA,{'&',EA},{']'}; (*Levels must be linear associated*) |
| EA | = LABELA \| FUNKA; |
| LABELA | = ['#'],LEVEL,('=' \| '==' \| '!=' \| '=~' \| '!~'),LABELALTERNATIVES; |
| FUNKA | = POSA \| NUMA; |
| POSA | = POSFCT, '(',LEVEL,',',LEVEL,')','=','0'\| '1'; (*Levels must be hierarchically or sequentially associated*) (*second level determines semantic*) |
| NUMA | = 'Num','(',LEVEL,',',LEVEL,')',VOP,INTPN; (*Levels must be hierarchically or sequentially associated*) (*first level determines semantic*) |
| LABELALTERNATIVES | = LABEL , {'|',LABEL}; |
| LABEL | = LABELING \| (“'“,LABELING,“'“); (*LEVEL levels must be part of the database structure*) (*LABELING is an arbitrary charcter string or a label group class configured in the emuDB*) (*The result modifier hash tag '#' must only occur once*)



| POSFCT = | 'Start'\|'Medial'\|'End'; |
| VOP =  | '=' \| '==' \| '!=' \| '>' \| '<' \| '<=' \| '>='; |
| INTPN = | '0' \| INTP; |
| INTP = | DIGIT-'0',{DIGIT}; |
| DIGIT = | '0'\|'1'\|'2'\|'3'\|'4'\|'5'\|'6'\|'7'\|'8'\|'9'; |

## Limitations 
One query can only contain one result modifier '#' (hashtag)


# Examples

## Examples adapted from [@harrington:2002],[@cassidy_harrington:2001]

**1. Simple queries (one argument)**

- All m elements on level Phonetic: **`[Phonetic = m]`**
- m or n elements on level Phonetic: **`[Phonetic = m | n]`**
- All elements except m oder n: **`[Phonetic != m | n]`**
- All syllables (Assuming that no syllable x exists): **`[Syllable !=x ]`**
- All syllables: **`[Syllable =~.* ]`**
- All Text level elements beginning with 'fi': **`[Text=~fi.*]`**

**2. Sequence queries ->**  
   **2.1. Simple sequences**  
   The arguments are connected with **->** (follows).  
   Syntax: **[L = a -> L = b]**  
   Semantic: Element a on level L precedes elemnt b on level L, both arguments must be on the same level (or linear level)  
A sequence of m I segments on the Phonetic level **`[Phonetic = m -> Phonetic = I]`**  
( all elements in the segent list have start time of m and end time of I)  
Same as above – but we want only m elements as result **`[#Phonetic = m -> Phonetic = I]`**  
(start time of m, end time of m)  
Same, but only I elements as result   **`[Phonetic = m -> # Phonetic = I]`**  

**2.2. Subsequent sequences**  
A sequence of arguments a1, a2, a3, a4, can be queried this way  
**[[[[a1-> a2] ->a3]->a4] ->a5]**  
All sequences of [m I n]  
**`[[ Phonetic = m -> Phonetic = I ] -> Phonetic = n ]`**  
all sequences of ‘john could lend’ (on Text level)  
**`[[ Text = john -> Text = could ] -> Text = lend ]`**  
‘the’, then arbitrary two words, then ‘managed’ (all on Text level, assume no word x exists)  
**`[[[ Text = the -> Text != x ] -> Text !=x ] -> Text = managed]`**  
same using EQL2 regular expression operator  
**`[[[ Text = the -> Text =~ .* ] -> Text =~ .* ] -> Text = managed]`**

**3. Boolean &**  
Syntax: **[L1=a &L2=b&L3=c&L4=d&...Ln=n]**  
Semantics: All a elements on level L1 which have properties b, c, d..n as well.  
Condition: All arguments must be on the same level or linear level  
S syllables which are labeled with L+H* too  
**`[Syllable = S & Pitch_Accent=L+H*]`**  
Text of all function words  
**`[Text !=x & Word = F]`**  
Text of all content words which are also accentuated (S)  
**`[Text!=x & Word=C & Accent=S]`**  

**4. Domination**
Syntax: Semantik: **[L1=a^ L2=b]**  
Semantics: a dominated by b or a dominated by b  
Condition: L1 dominates L2 or L2 dominates L1

**4.1. Simple Domination**
All /p/ phonemes in S Syllables  
**`[Phoneme = p ^ Syllable = S]`**  
All syllables, which contain a phonmeme /p/  
**`[Syllable !=x ^ Phoneme = p]`**  
or  
**`[Phoneme = p ^ #Syllable !=x]`**  
All syllables, which neither contain /k/ nor /p/ nor /t/  
**`[Syllable!=x ^ Phoneme != p | t | k]`**  
oder  
**`[Phoneme != p | t | k ^ # Syllable !=x ]`**

**4.2. Multiple Domination**  
A dominance relationship sequnce a1, a2, a3, a4, is noted this way:  
**[[[[a1^ a2] ^a3]^a4] ^a5]**  
H\* syllables containing a phoneme /p/, dominated by words ‘price’ or ‘space'  
**`[[Pitch_Accent=H\* ^ Phoneme=p] ^ Text = price|space]`**  
The same – but we want the  appropriate words  
**`[[Pitch_Accent=H* ^ Phoneme=p] ^ #Text = price|space]`**  


**5. Position**  
**5.1 Simple usage**  
Syntax: **Start(La, Lb) = 1  **
Semantics: Lb occurs at the beginning of La
Condition: La dominates Lb  
Note: Simple usage generates the segment list of Lb
e.g.:
Syllables at begining of word **`[Start(Word, Syllable)=1]`**
Phonemes at begining of word **`[Start(Word, Phoneme)=1]`**
Syllables not at begining of word **`[Start(Word, Syllable)=0]`**
Functions Medial(La, Lb) and End(La, Lb)
Word-final syllables **`[End(Word, Syllable)=1]`** and so on  

**6. Position und Boolean &**  
Syntax: L = e & Start(La, Lb) = 1  
Semantics: Element e on level L occurs at the bginning of La  
Condition: La dominates Lb  (L and Lb are on the same level or linear level).  

e.g.:
all /p/ phonemes at the beginning of a syllable  
**`[Phoneme = p & Start(Syllable, Phoneme)=1]`**  
All word-final /m/ phonemes  
**`[Phoneme = m & End(Word, Phoneme)=1]`**  
All non-word-final S syllables which are labeled with tonic accent L+H*  
**`[Syllable =S & Pitch_Accent=L+H* & (Word, Syllable)=0]`**  

**6.1. Position und Boolean ^**  
Syntax/Semantics as for 5.2, but:
If L und Lb are different levels (L dominates Lb, or Lb dominates L) use ^ instead of & :
/p/ phonemes, which occur in the first syllable of the word  
**`[Phoneme = p ^ Start(Word, Syllable)=1]`**  
All phonemes, which do not occur in the last syllable of the word  
**`[Phoneme !=x ^ End(Word, Syllable)=0]`**  

**7. Count**  
**Simple usage**  
Syntax: **Num(La, Lb) = n**
Semantics: La contains n Lb elements
Condition: La dominates Lb. n is a number
Note: Generates segment list on La (not on Lb, as with 4-syllable words position)
**`[Num(Word, Syllable)=4]`**  
There are also the operators > (more than), < (less than) and != (not equal).  
Syllables, which have more than 6 phonemes
**`[Num(Syllable, Phoneme)>6]`**  
and so on  

**7.1. Count and Boolean &**  
Syntax: **L = e & Num(La, Lb) = n**  
Semantics: Element e on level L is dominated by La ; and La contains n Lb elements, La dominates Lb  
Condition: (L and La (not Lb!) are on the same level or linear level).  
Text of all words, which consist of 11 phonemes:  
**`[Text!=x & Num(Text, Phoneme) > 11 ] =`**  
or  
**`[Text=~.* & Num(Word, Phoneme) > 11 ]`**  
H* tonic accents in syllables of 5 phonemes:  
**`[Pitch_Accent = H* & Num(Syllable, Phoneme) = 5]`**  

**7.2. Count and ^**  
Syntax/Semantics as with 6.2, but:
If L and La are different levels (L dominates La, or La dominates L) use ^ instead of & :
All m phonemes in 4-syllable words  
**`[Phoneme=m ^ Num(Word, Syllable)=4]`**
All W-Syllables in words of 3 or less syllables
**`[Syllable = W ^ Num(Word, Syllable) < 3]`**  
All words, which contain syllable, which contain 4 phonemes  
**`[Text!=x ^ Num(Syllable, Phoneme) = 4]`**

**8. Combinations **  
**8.1. ^ und -> (Domination and Sequence)  
Condition: The sequence -> must connect only same or levels or linear levels! (See 2.)  
**[[a1 ^ a2] -> a3] [a1 -> [a2 ^ a3]]**  
m precedes I and m is part of a S-syllable  
**`[[Phoneme = m -> Phoneme = I] ^ Syllable=S]`**  
s precedes p and p is part of a W-syllable  
**`[Phoneme = s -> [Phoneme = p ^ Syllable = W]]`**  
all S-syllables, which contain phoneme p and precede a S-syllable  
**`[[Syllable = S ^ Phoneme = p] -> Syllable = S]`**  
but now we want p: p is part of a S-syllable and this S-syllable precedes a S-syllable  
**`[[Phoneme = p ^ Syllable = S] -> Syllable = S]`**  
Not allowed! Because Phoneme = p and Syllable = S are not on the same level, therefore:  
**`[[Syllable = S ^ #Phoneme=p] -> Syllable = S]`**  

**8.2. ^ and -> and & (Domination and Sequence and Boolean &)**  
Words, beginning with a schwa:  
**`[Text!=x ^ Phoneme = @ & Start(Text, Phoneme)=1]`**
A word-begining m in a string syllbale, which precedes I  
**`[[Phoneme = m & Start(Word, Phoneme)=1 -> Phoneme=I] ^ Syllable=S]`**  
same but we want the text:  
**`[[[Phoneme = m & Start(Word, Phoneme)=1 -> Phoneme=I] ^ Syllable=S] ^ #Text!=x]`**
The text of all three-syllable words, which contain a schwa in the first syllable; these three-syllable words must precede ‘the’
The text of all three-syllable words  
1. Text!=x & Num(Text, Syllable)=3  
Schwa occurs in the first syllable  
2. Phoneme=@ ^ Start(Word, Syllable)=1  
The text is ‘the’  
3. Text = the  
[1 ^ 2]  
[[1 ^ 2] -> 3]

**`[[Text!=x & Num(Text, Syllable) =3 ^ [Phoneme=@ ^ Start(Word, Syllable)=1]] -> Text=the ]`**  

##**Questions**
1. m or n phonemes, which occur in the middle of the word.  
2. [H] phonetic segments, next an arbitrary segment, next either [I] or [U].  
3. Syllables, which do not occur in the middle of a word.  
4. The text of all words, which contain two syllables.  
5. The text of all accentuated words following ‘the’.  
6. S syllables consisting of 5 phonemes.  
7. W syllables, which contain a /@/ phoneme.  
8. The text of words, which contain either a L\* or L\+H\* a tonic accent.  
9. H\* tonic accents of word-final syllables, which occur in three-syllable words.  
10. All phonemes, domaibnting Phonetic element [H], at the beginning of a syllable; and which occur in accentuated (S) words.  

##**Answers**
1. m or n phonemes, which occur in the middle of the word.  
`[Phoneme = m | n & Medial(Word, Phoneme)=1]`  
2. [H] phonetic segments, next an arbitrary segment, next either [I] or [U].  
`[ [Phonetic = H -> Phonetic !=x ] -> Phonetic = I | U ]`  
3.  Syllables, which do not occur in the middle of a word.  
`[Syllable!=x & Medial(Word, Syllable)=0]`  
4.The text of all words, which contain two syllables.  
`[Text!=x & Num(Text, Syllable)=2]`  
5. The text of all accentuated words following ‘the’.  
`[Text = the -> #Text!=x & Accent = S]`  
6. S syllables consisting of 5 phonemes.  
`[Syllable = S ^ Num(Word, Phoneme)=5]`  
7.  W syllables, which contain a /@/ phoneme.  
`[Syllable = W ^ Phoneme=@]`  
8. The text of words, which contain either a L\* or L\+H\* a tonic accent.  
`[Text!=x ^ Pitch_Accent = L* | L+H*]`
9. H\* tonic accents of word-final syllables, which occur in three-syllable words.  
`[Pitch_Accent = H* & End(Word, Syllable)=1 ^ Num(Word, Syllable) =3]`  
10. All phonemes, domaibnting Phonetic element [H], at the beginning of a syllable; and which occur in accentuated (S) words.  
`[[[Phoneme!=x ^ Phonetic = H] ^ Start(Word, Syllable)=1] ^ Accent = S]`  


# Differences and incompatibilities to legacy EMU query language (R package version 4.2)

## Function call syntax
For emuR it is required that the emuDB is loaded in current R session.
EQL2 query function is part of R package emuR. See help(query)  
Examples:
```
query('andosl',"[Phoneme = p ^ Syllable = S]")
```

Session and bundle selection patterns are optional and expect regular expression pattrens.

Example:
```
query('andosl',"[Phoneme = p ^ Syllable = S]",sessionPattern='000.',bundlePattern='msajc0[1-2].')
```

Parameter sessionPattern has no effect here (andosl is a legacy import emuDB and has only one dummy session '0000').  
Parameter bundlePattern selects all bundle names starting with 'msajc01' or 'msajc02'.


## Result type

Default result type of a query is an object of R S3 class 'emuRsegs'. The class inherits legacy Emu class 'emusegs' and R standard class 'data.frame'.
Each row of this data.frame is a sequence of one or more annotation elements on one level; a segment.   
Details:
```
help(emuRsegs)
```
emuR returns an empty segment list (zero row count) if the query does not match any element, in opposite to legacy Emu which throws an error ("Can't find the query results in emu.query: there may have been a problem with the query command.")


## Bundle (utterance) names

emuR package arranges bundles (utterances) in sessions. Converted legacy EMU databases have one default session '0000' containing all bundles. Therefore the 'utts' column of all segment lists is prefixed by the session name and starts with '0000:' for example '0000:msajc003'.
See emuDB vigniette for details.

## The result modifier hash tag '#'

Legacy Emu allows multiple occurences of the hash tag '#' in a query.

emuR allows only one single hash tag '#' in a query.

If you want multiple results in one segment list, it is recommended do concatenate the results of separate queries and position the hash tag to different places in these queries to get desired results.

## Interpretation of the hash character '#' in logical AND combined terms
#### legacy Emu
```
> emu.query('andosl','*','[Text=spring & #Accent=S]')
moving data from Tcl to R
Read 1 records
segment  list from database:  andosl 
query was:  [Text=spring & #Accent=S] 
  labels    start      end     utts
1 spring 2288.959 2704.466 msajc094

> emu.query('andosl','*','[#Text=spring & #Accent=S]')
moving data from Tcl to R
Read 1 records
segment  list from database:  andosl 
query was:  [#Text=spring & #Accent=S] 
  labels    start      end     utts
1 spring 2288.959 2704.466 msajc094
```
The hash character has no effect to both queries

#### emuR
```
> query(andosl,"[Text=spring & #Accent=S]",resultType='emusegs')
segment  list from database:  andosl 
query was:  [Text=spring & #Accent=S] 
  labels    start      end          utts
1      S 2288.975 2704.475 0000:msajc094
```
Returns the same segment (same item), but with the label of the hashed attribute name.
The second legacy example is not valid in emuR query (two has tags).

```
> query('andosl',"[#Text=spring & #Accent=S]")

 Error in query.database.eql.KONJA(dbConfig, qTrim) : 
  Only one hashtag allowed in linear query term: #Text=spring & #Accent=S 
```

EQL2 throws an error here, because to fulfill the request it would be necessary to return each item doubled to get both Text and Accent labels  

## Probable bugs in legacy EMU EQL

### Alternative labels in not equal conditional query
Example:
#### (legacy) emu
```
> emu.query('ae','*',"[Text!=beautiful|futile ^ Phoneme=u:]")
moving data from Tcl to R
Read 4 records
segment  list from database:  ae 
query was:  [Text!=beautiful|futile ^ Phoneme=u:] 
     labels    start      end     utts
1       new  475.802  666.743 msajc057
2    futile  571.999 1091.000 msajc010
3        to 1091.000 1222.389 msajc010
4 beautiful 2033.739 2604.489 msajc003
```
I assume that the OR operator '|' is ignored in connection with the not equal operator '!='

#### emuR
```
> query(ae,"[Text!=beautiful|futile ^ Phoneme=u:]",resultType='emusegs')
segment  list from database:  ae 
query was:  [Text!=beautiful|futile ^ Phoneme=u:] 
  labels    start      end          utts
1     to 1091.025 1222.375 0000:msajc010
2    new  475.825  666.725 0000:msajc057
```

### Errors caused by missing blanks

Legacy Emu query requires blanks around some operators or brackets in some queries. If these blanks are missing compiler errors or even crashes will occur for some query strings. 

emuR accepts these queries without blanks.

### Additional features

emuR accepts also the double equal character string '==' as equal operator.

emuR EQL2 has the capability to query labels by matching regular expressions using the '=~' (match) and '!~' (not match) operators.

#### Example
```
> query('andosl',"Text=~.*tz.*")
segment  list from database:  andosl 
query was:  Text=~.*tz.* 
   labels    start      end session   bundle startItemID endItemID type
1 blitzed 1586.875 2112.475    0000 msadb081          54        54 ITEM
2 blitzed 1540.225 2022.475    0000 msajc081          59        59 ITEM
```

# References