! this file was generated by tpled

level Utterance 
level Intonational Utterance 
level Intermediate Intonational 
level Word Intermediate 
level Syllable Word 
level Phoneme Syllable 
level Phonetic Phoneme many-to-many 
level Tone Syllable 
level Foot Intonational 
level Syllable Foot 


label Word Accent 
label Word Text 



labfile Phonetic :type SEGMENT :extension lab :time-factor 1000 
labfile Tone :type EVENT :extension tone :time-factor 1000 


legal Phoneme vowel A E I O V U ai ei oi i@ u@ au @u @: @ a: e: i: o: u:

legal Phoneme stop p tS dZ t k b d g

legal Phoneme nasal m n N

legal Phoneme fricative f v s z S Z h D T

legal Phoneme approximant w j l r

legal Phoneme other H


legal Phonetic vowel A E EC I O V U ai ei oi i@ u@ au @u @: @ = a: e: i: o: u:

legal Phonetic stop p tS dZ t k b d g

legal Phonetic nasal m n

legal Phonetic fricative f v s z S Z h D D- T

legal Phonetic approximant w j l r rr Or

legal Phonetic other H




path lab labels
path tone labels
path hlb labels
path wav signals
path dft signals
path fms signals


track samples wav
track dft dft
track fm fms


set PrimaryExtension wav
set LabelTracks spectrogram 
set HierarchyViewLevels Intonational Intermediate Word Syllable Phoneme 
set SignalViewLevels Phonetic Tone 

 
